### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by shandilyasaurav405**
Now, it is in effect.

### CODE REVIEW

**Comment by priyank-svmx** [comment]
why is this pull request raised?

**Comment by shandilyasaurav405** [comment]
because it is now apply in react and in the repo it is not mentioned

**Comment by shandilyasaurav405** [comment]
reimplementation of React's core algorithm.

it is implemented now so i raised a PR

**Comment by shradiphylleia** [comment]
@shandilyasaurav405 if you wanted to raise a PR to that effect- should have just deleted the word "ongoing". The word reimplementation suggests that Fiber is reimplementing the core React algorithm. The removal of the word reimplementation actually seems kind of unfit given the context.

**Comment by eddyw** [comment]
There is 5 open PRs titled "Update README.md" and 3 of them are exactly like this one.

Here is a life hack for you to continue faking GitHub progress: create your own repo, open a PR on your own repo, and update your own README.md

**Comment by priyank-svmx** [comment]
@shandilyasaurav405  my humble request, please close this PR.

**Comment by shandilyasaurav405** [comment]
Ok, I will do it.

**Pull request closed without merging**
